baseURL: "https://actualdesignstudio.ro"
disableKinds:
  - section
  - taxonomy
  - term
  - RSS
  - robotsTXT
defaultContentLanguage: en
theme: hugo-scroll-master
title: ACTUAL Design Studio
params:
  copyright: © ActualDesignStudio
  description: Actual Design Studio
  favicon: images/favicon.png
  images:
    - images/cover-image.jpg
  title: Actual Design Studio
  meta:
    keywords: "design, interior, colors"
